### ISSUE TITLE
Errors when getting train data using the script "get_test_data_v2.py"

### ISSUE THREAD

**Issue by JoshuaChen712** [ImageArg/ImageArg-Shared-Task#1]
When I run get_test_data_v2.py, I got these error messages:
`Traceback (most recent call last):
  File "/Users/zoee/Desktop/ImageArg-Shared-Task-main/get_test_data_v2.py", line 21, in <module>
    from plugins.macos_silicon import get_test_data_with_labels
ImportError: dlopen(/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so, 0x0002): tried: '/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so' (code signature in <7740E98F-CF5F-32C9-AA82-63A1FE07C603> '/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so' (no such file), '/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so' (code signature in <7740E98F-CF5F-32C9-AA82-63A1FE07C603> '/Users/zoee/Desktop/ImageArg-Shared-Task-main/plugins/macos_silicon.so' not valid for use in process: library load disallowed by system policy)`
Could you plz tell me what should I do to get the data?

**Comment by ZhexiongLiu** [comment]
The code will work best with macOS-ARM/X86 and Ubuntu/Debian systems with a Python 3.9 environment. If you are macOS users please install XCode (xcode-select --install). If you are Linux users please install essential build tools (sudo apt-get install build-essential).

**Comment by JoshuaChen712** [comment]
Thank you for your help! I've solved this problem.
